server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-log-files
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /logs/*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: "[\"@timestamp\"]"
            service: service
            host: host
            environment: environment
            level: level
            logger: logger_name
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          service:
          environment:
          level:

  - job_name: local-log-files
    static_configs:
      - targets:
          - localhost
        labels:
          job: local-logs
          __path__: /local-logs/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: "[\"@timestamp\"]"
            service: service
            host: host
            environment: environment
            level: level
            logger: logger_name
            message: message
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          service:
          environment:
          level:
